#!/bin/bash


STATE=$(cat /opt/terraform/aws/terraform.tfstate)
export AWS_ACCESS_KEY_ID=$(cat /opt/terraform/aws/terraform.tfvars | grep "aws_access_key" |  cut -d'"' -f2)
export AWS_SECRET_ACCESS_KEY=$(cat /opt/terraform/aws/terraform.tfvars | grep "aws_secret_key" |  cut -d'"' -f2)
export AWS_DEFAULT_REGION=$(cat /opt/terraform/aws/terraform.tfvars | grep "aws_region" |  cut -d'"' -f2)
SERVER_ID=$(echo "$STATE"  | jq '.outputs.rancher_server_ec2_instance_id.value')
SERVER_ID=$(echo "${SERVER_ID//\"/ }")
aws ec2 configure
echo "Try to awake server :${SERVER_ID}"
aws ec2 start-instances --instance-ids $SERVER_ID
echo "Waiting for to start server :${SERVER_ID}"
aws ec2 wait instance-status-ok --instance-ids $SERVER_ID
echo "server :${SERVER_ID} started"