#!/bin/bash

TERRAFORM_STATE=$(cat /opt/terraform/aws/terraform.tfstate)

SERVER_ID=$(echo $TERRAFORM_STATE  | jq '.outputs.rancher_server_ec2_instance_id.value')
SERVER_ID=$(echo "${SERVER_ID//\"/ }")

export AWS_ACCESS_KEY_ID=$(cat /opt/terraform/aws/terraform.tfvars | grep "aws_access_key" |  cut -d'"' -f2)
export AWS_SECRET_ACCESS_KEY=$(cat /opt/terraform/aws/terraform.tfvars | grep "aws_secret_key" |  cut -d'"' -f2)
export AWS_DEFAULT_REGION=$(cat /opt/terraform/aws/terraform.tfvars | grep "aws_region" |  cut -d'"' -f2)

aws ec2 describe-instance-status --instance-ids $SERVER_ID | jq '.InstanceStatuses'
echo "Try to stop server :${SERVER_ID}"
aws ec2 stop-instances --instance-ids $SERVER_ID
echo "Waiting for to stop server :${SERVER_ID}"
aws ec2 wait instance-stopped --instance-ids $SERVER_ID
echo "server :${SERVER_ID} stopped"